# Generated by Django 4.0 on 2025-04-20 21:09

import GVS.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abanderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
            ],
            options={
                'ordering': ['-creado_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('es_responsable', models.BooleanField(default=False)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
            ],
            options={
                'ordering': ['-fecha_asignacion'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de contratación')),
                ('tipo_contrato', models.CharField(choices=[('TIEMPO_COMPLETO', 'Tiempo completo'), ('MEDIO_TIEMPO', 'Medio tiempo'), ('TEMPORAL', 'Temporal')], max_length=20, verbose_name='Tipo de contrato')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20, verbose_name='Estado del empleado')),
                ('comentario_status', models.TextField(blank=True, null=True, verbose_name='Comentario sobre el estado')),
                ('fecha_inactivacion', models.DateField(blank=True, null=True, verbose_name='Fecha de inactivación (si aplica)')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['-fecha_contratacion'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-creado_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('abanderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GVS.abanderado')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GVS.empresa')),
            ],
            options={
                'ordering': ['-creado_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('numero_vacantes', models.PositiveIntegerField()),
                ('nivel_experiencia', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto'), ('Híbrido', 'Híbrido')], max_length=20)),
                ('departamento', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('Tiempo completo', 'Tiempo completo'), ('Medio tiempo', 'Medio tiempo'), ('Temporal', 'Temporal')], max_length=20)),
                ('fecha_maxima_postulacion', models.DateField()),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('categoria', models.CharField(max_length=100)),
                ('salario_ofrecido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GVS.empresa')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GVS.estacion')),
            ],
            options={
                'ordering': ['-creado_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.PositiveIntegerField(editable=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacaciones', to='GVS.empleado')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Vacaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('cv', models.FileField(blank=True, null=True, upload_to=GVS.models.Solicitante.cv_upload_path)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=GVS.models.Solicitante.foto_upload_path)),
                ('direccion', models.TextField()),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GVS.vacante')),
            ],
            options={
                'ordering': ['-creado_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_pedido', models.CharField(max_length=50, unique=True)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('JSON', 'JSON')], default='PDF', max_length=10)),
                ('parametros', models.JSONField(default=dict)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='informes/')),
                ('contenido', models.JSONField(default=list)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Informes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Entrevistador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
            ],
            options={
                'ordering': ['-creado_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('asunto', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=20)),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('lugar', models.CharField(max_length=255)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
                ('entrevistador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GVS.entrevistador')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GVS.solicitante')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GVS.vacante')),
            ],
            options={
                'ordering': ['-creado_en'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GVS.empresa', verbose_name='Empresa asociada'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estaciones',
            field=models.ManyToManyField(through='GVS.AsignacionEstacion', to='GVS.Estacion', verbose_name='Estaciones asignadas'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='solicitante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='GVS.solicitante'),
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('dias_base', models.PositiveIntegerField(default=10, help_text='Días base según primer año de servicio (Art. 346 Código Trabajo)', verbose_name='Días Base Anuales')),
                ('dias_adicionales', models.PositiveIntegerField(default=0, help_text='Días extras por antigüedad (+1 día por año después del primero)', verbose_name='Días Adicionales')),
                ('dias_tomados', models.PositiveIntegerField(default=0, help_text='Días de vacaciones ya consumidos', verbose_name='Días Utilizados')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to='auth.user')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to='auth.user')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='GVS.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Beneficio de Vacaciones',
                'verbose_name_plural': 'Beneficios de Vacaciones',
                'ordering': ['empleado__solicitante__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('C', 'Creación'), ('A', 'Actualización'), ('E', 'Eliminación'), ('L', 'Inicio de Sesión'), ('S', 'Cierre de Sesión'), ('I', 'Intento Fallido')], max_length=1)),
                ('modelo_afectado', models.CharField(max_length=50)),
                ('id_objeto', models.CharField(blank=True, max_length=20, null=True)),
                ('detalles', models.JSONField(default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='asignacionestacion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GVS.empleado'),
        ),
        migrations.AddField(
            model_name='asignacionestacion',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GVS.estacion'),
        ),
        migrations.AddConstraint(
            model_name='beneficio',
            constraint=models.CheckConstraint(check=models.Q(('dias_tomados__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('dias_base'), '+', django.db.models.expressions.F('dias_adicionales')))), name='check_dias_tomados_no_superan_total'),
        ),
    ]
