# Generated by Django 4.0 on 2025-04-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GVS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estaciones',
            field=models.ManyToManyField(blank=True, through='GVS.AsignacionEstacion', to='GVS.Estacion', verbose_name='Estaciones asignadas'),
        ),
    ]
